# Generated by Django 2.2.3 on 2019-07-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_auto_20190710_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
