# Generated by Django 2.2.3 on 2019-08-02 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20190710_1401'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficLog',
        ),
    ]
