# Generated by Django 2.2.3 on 2019-08-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_trafficlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
